In [5]:
print("Hello World");

Hello World


In [6]:
import numpy as np
import math

In [7]:
import pandas as pd;
import matplotlib;

In [8]:
import matplotlib.image as mpimg
import matplotlib.pyplot as plt



In [9]:
print(np.__version__);

1.19.5


In [10]:

import os

def read_all_files_in_directory(directory_path):
    """
    Reads the content of all files in a specified directory.

    Args:
        directory_path (str): The path to the directory to read files from.

    Returns:
        dict: A dictionary where keys are filenames and values are their content.
              Returns an empty dictionary if the directory does not exist or
              contains no readable files.
    """
    file_contents = {}
    datasetimages=np.zeros((12499,400));
    c=0;
    ##datasetimages=np.zeroes(12,499,)
    if not os.path.isdir(directory_path):
        print(f"Error: Directory '{directory_path}' does not exist.")
        return file_contents

    for filename in os.listdir(directory_path):
        filepath = os.path.join(directory_path, filename)
        if os.path.isfile(filepath):
            try:
                
                im=mpimg.imread(filepath);
                print(im.shape);
                im_flattened=im.flatten();
                print(im_flattened.shape);
                ##padwidth=800000-im_flattened.shape[0];
                ##im_flattened=np.pad(im_flattened,pad_width=padwidth,mode="constant",constant_values=0);
                im_flattened=im_flattened[0:400];
                datasetimages[c,]=im_flattened;
                
                """with open(filepath, 'r', encoding='utf-8') as f:
                    content = f.read()
                    file_contents[filename] = content"""
            except Exception as e:
                print(f"Could not read file '{filename}': {e}")
        c=c+1;
        print("Read",c,"images upto now");
    return datasetimages;

# Example usage:
target_directory = "C:/Users/parth/Downloads/archive(2)/PetImages/Cat"; # Replace with your directory path
all_files_data = read_all_files_in_directory(target_directory);

target_directory2="C:/Users/parth/Downloads/archive(2)/PetImages/Dog";
all_files_data2=read_all_files_in_directory(target_directory2);

"""for filename, content in all_files_data.items():
    print(f"--- Content of {filename} ---")
    print(content)
    print("-" * 30)"""

(375, 500, 3)
(562500,)
Read 1 images upto now
(281, 300, 3)
(252900,)
Read 2 images upto now
(500, 489, 3)
(733500,)
Read 3 images upto now
(500, 403, 3)
(604500,)
Read 4 images upto now
(150, 150, 3)
(67500,)
Read 5 images upto now
(360, 431, 3)
(465480,)
Read 6 images upto now
(375, 500, 3)
(562500,)
Read 7 images upto now
(471, 500, 3)
(706500,)
Read 8 images upto now
(375, 500, 3)
(562500,)
Read 9 images upto now
(240, 320, 3)
(230400,)
Read 10 images upto now
(177, 320, 3)
(169920,)
Read 11 images upto now
(320, 461, 3)
(442560,)
Read 12 images upto now
(300, 220, 3)
(198000,)
Read 13 images upto now
(375, 500, 3)
(562500,)
Read 14 images upto now
(500, 473, 3)
(709500,)
Read 15 images upto now
(500, 336, 3)
(504000,)
Read 16 images upto now
(386, 500, 3)
(579000,)
Read 17 images upto now
(448, 358, 3)
(481152,)
Read 18 images upto now
(167, 250, 3)
(125250,)
Read 19 images upto now
(375, 500, 3)
(562500,)
Read 20 images upto now
(500, 373, 3)
(559500,)
Read 21 images upto now
(3

c:\Users\parth\anaconda3\envs\ParthaNLP2\lib\site-packages\PIL\TiffImagePlugin.py:819: UserWarning: Truncated File Read
  warnings.warn(str(msg))



(230400,)
Read 11439 images upto now
(375, 500, 3)
(562500,)
Read 11440 images upto now
(375, 372, 3)
(418500,)
Read 11441 images upto now
(200, 164, 3)
(98400,)
Read 11442 images upto now
(375, 500, 3)
(562500,)
Read 11443 images upto now
(311, 231, 3)
(215523,)
Read 11444 images upto now
(320, 224, 3)
(215040,)
Read 11445 images upto now
(375, 500, 3)
(562500,)
Read 11446 images upto now
(466, 500, 3)
(699000,)
Read 11447 images upto now
(375, 500, 3)
(562500,)
Read 11448 images upto now
(423, 435, 3)
(552015,)
Read 11449 images upto now
(400, 239, 3)
(286800,)
Read 11450 images upto now
(375, 500, 3)
(562500,)
Read 11451 images upto now
(375, 500, 3)
(562500,)
Read 11452 images upto now
(314, 413, 3)
(389046,)
Read 11453 images upto now
(500, 389, 3)
(583500,)
Read 11454 images upto now
(375, 500, 3)
(562500,)
Read 11455 images upto now
(148, 181, 3)
(80364,)
Read 11456 images upto now
(500, 423, 3)
(634500,)
Read 11457 images upto now
(200, 223, 3)
(133800,)
Read 11458 images upto

'for filename, content in all_files_data.items():\n    print(f"--- Content of {filename} ---")\n    print(content)\n    print("-" * 30)'

In [11]:
print(all_files_data);

[[203. 164.  87. ... 138.  86. 227.]
 [ 36.  41.  37. ...  84.  97. 135.]
 [ 25.  29.  38. ...  54.  66.  47.]
 ...
 [ 96.  98. 119. ... 112.  96. 147.]
 [ 59.  60.  62. ... 182. 182. 166.]
 [137. 163. 176. ... 173. 191. 143.]]


In [12]:
X_data1=all_files_data;
y_data1=np.ones(all_files_data.shape[0])
print(y_data1.shape);


X_data2=all_files_data2;
y_data2=np.zeros(all_files_data2.shape[0])
print(y_data2.shape)

(12499,)
(12499,)


In [13]:
df=pd.DataFrame(X_data1);
print(df);



         0      1      2      3      4      5      6      7      8      9    \
0      203.0  164.0   87.0  203.0  164.0   87.0  204.0  165.0   88.0  205.0   
1       36.0   41.0   37.0   37.0   42.0   38.0   38.0   42.0   41.0   38.0   
2       25.0   29.0   38.0   23.0   27.0   36.0   19.0   23.0   32.0   13.0   
3      223.0  224.0  219.0  223.0  224.0  219.0  223.0  224.0  219.0  223.0   
4      133.0  107.0   70.0  137.0  109.0   70.0  143.0  114.0   74.0  148.0   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
12494   24.0   24.0   24.0   24.0   24.0   24.0   23.0   23.0   23.0   22.0   
12495   91.0   98.0  114.0   93.0  100.0  116.0   94.0  101.0  117.0   93.0   
12496   96.0   98.0  119.0   92.0   94.0  115.0   91.0   93.0  114.0   92.0   
12497   59.0   60.0   62.0   58.0   58.0   60.0   59.0   54.0   58.0   59.0   
12498  137.0  163.0  176.0  140.0  160.0  171.0  106.0  115.0  124.0   43.0   

       ...    390    391    392    393    394    39

In [14]:
df1=pd.DataFrame(X_data2);
print(df1);

         0      1      2      3      4      5      6      7      8      9    \
0      117.0  115.0  126.0  117.0  115.0  126.0  119.0  117.0  130.0  121.0   
1      255.0  253.0  244.0  219.0  209.0  199.0  212.0  196.0  181.0  231.0   
2      149.0  119.0   65.0  139.0  108.0   53.0  136.0  101.0   45.0  136.0   
3      197.0  186.0  182.0  197.0  186.0  182.0  197.0  186.0  182.0  197.0   
4        5.0    4.0    2.0   10.0   10.0    8.0   13.0   13.0   15.0   12.0   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
12494  147.0  143.0  106.0  148.0  144.0  107.0  149.0  145.0  108.0  150.0   
12495  157.0  128.0   98.0  144.0  115.0   85.0  145.0  118.0   88.0  104.0   
12496   46.0   41.0   37.0   55.0   50.0   46.0   60.0   55.0   51.0   59.0   
12497  252.0  252.0  250.0  252.0  252.0  250.0  252.0  252.0  250.0  250.0   
12498  248.0  240.0  229.0  251.0  243.0  232.0  253.0  245.0  234.0  252.0   

       ...    390    391    392    393    394    39

In [15]:
df["label"]=y_data1;
df1["label"]=y_data2;

In [16]:
print(df);
print(df1);

           0      1      2      3      4      5      6      7      8      9  \
0      203.0  164.0   87.0  203.0  164.0   87.0  204.0  165.0   88.0  205.0   
1       36.0   41.0   37.0   37.0   42.0   38.0   38.0   42.0   41.0   38.0   
2       25.0   29.0   38.0   23.0   27.0   36.0   19.0   23.0   32.0   13.0   
3      223.0  224.0  219.0  223.0  224.0  219.0  223.0  224.0  219.0  223.0   
4      133.0  107.0   70.0  137.0  109.0   70.0  143.0  114.0   74.0  148.0   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
12494   24.0   24.0   24.0   24.0   24.0   24.0   23.0   23.0   23.0   22.0   
12495   91.0   98.0  114.0   93.0  100.0  116.0   94.0  101.0  117.0   93.0   
12496   96.0   98.0  119.0   92.0   94.0  115.0   91.0   93.0  114.0   92.0   
12497   59.0   60.0   62.0   58.0   58.0   60.0   59.0   54.0   58.0   59.0   
12498  137.0  163.0  176.0  140.0  160.0  171.0  106.0  115.0  124.0   43.0   

       ...    391    392    393    394    395    39

In [17]:
final_df=pd.concat([df,df1]);


In [18]:
print(final_df);
final_df.shape;

           0      1      2      3      4      5      6      7      8      9  \
0      203.0  164.0   87.0  203.0  164.0   87.0  204.0  165.0   88.0  205.0   
1       36.0   41.0   37.0   37.0   42.0   38.0   38.0   42.0   41.0   38.0   
2       25.0   29.0   38.0   23.0   27.0   36.0   19.0   23.0   32.0   13.0   
3      223.0  224.0  219.0  223.0  224.0  219.0  223.0  224.0  219.0  223.0   
4      133.0  107.0   70.0  137.0  109.0   70.0  143.0  114.0   74.0  148.0   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
12494  147.0  143.0  106.0  148.0  144.0  107.0  149.0  145.0  108.0  150.0   
12495  157.0  128.0   98.0  144.0  115.0   85.0  145.0  118.0   88.0  104.0   
12496   46.0   41.0   37.0   55.0   50.0   46.0   60.0   55.0   51.0   59.0   
12497  252.0  252.0  250.0  252.0  252.0  250.0  252.0  252.0  250.0  250.0   
12498  248.0  240.0  229.0  251.0  243.0  232.0  253.0  245.0  234.0  252.0   

       ...    391    392    393    394    395    39

In [19]:
df_final=final_df.sample(frac=1,random_state=42);

In [20]:
print(df_final);

           0      1      2      3      4      5      6      7      8      9  \
6868    69.0   41.0   19.0   70.0   42.0   20.0   71.0   43.0   21.0   72.0   
10411  197.0  200.0  181.0  200.0  203.0  184.0  189.0  192.0  173.0  166.0   
9668    85.0   64.0   61.0   85.0   64.0   61.0   86.0   65.0   62.0   87.0   
1139   252.0  251.0  230.0  255.0  254.0  233.0  243.0  242.0  221.0  232.0   
10838  141.0  145.0   86.0  151.0  155.0   96.0  127.0  133.0   71.0  154.0   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
9076   122.0  101.0   96.0  126.0  105.0  100.0  129.0  108.0  103.0  127.0   
5390   250.0  247.0  242.0  251.0  248.0  243.0  250.0  249.0  245.0  244.0   
860     54.0   67.0   84.0   53.0   66.0   83.0   51.0   64.0   81.0   50.0   
3296   244.0  244.0  242.0  237.0  237.0  235.0  233.0  229.0  226.0  210.0   
11155  191.0  183.0  162.0  191.0  184.0  166.0  196.0  192.0  181.0  197.0   

       ...    391    392    393    394    395    39

In [21]:
final_X=df_final.to_numpy();

In [22]:
Xfinal=final_X[:,0:400];
print(Xfinal.shape);
Yfinal=final_X[:,400];
print(Yfinal.shape);


(24998, 400)
(24998,)


In [23]:
print(Yfinal);
print(Xfinal);

[1. 0. 1. ... 1. 0. 0.]
[[ 69.  41.  19. ... 112.  98. 105.]
 [197. 200. 181. ... 192. 177. 192.]
 [ 85.  64.  61. ... 204. 210. 203.]
 ...
 [ 54.  67.  84. ...  87. 105.  80.]
 [244. 244. 242. ... 242. 236. 249.]
 [191. 183. 162. ... 158. 169. 166.]]


In [24]:
import sklearn;

In [25]:
from sklearn.model_selection import train_test_split;

Xtrain,Xtest,ytrain,ytest=train_test_split(Xfinal,Yfinal,test_size=0.2,random_state=42);

In [26]:
print(Xtrain.shape);
print(Xtest.shape);
print(ytrain.shape);
print(ytest.shape);
##Standardization to be done

(19998, 400)
(5000, 400)
(19998,)
(5000,)


In [137]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler();
Xtrain_scaled=scaler.fit_transform(Xtrain);
Xtest_scaled=scaler.fit_transform(Xtest);

In [140]:
print(np.transpose(Xtrain_scaled[4,]).shape);
print(Xtrain_scaled[4,]);

(400,)
[-1.03093009 -0.8829269  -0.64325606 -1.01714021 -0.86942997 -0.62795698
 -1.02013245 -0.86988033 -0.63125963 -1.01098058 -0.86237398 -0.62165682
 -1.00224747 -0.852326   -0.58609819 -0.9862653  -0.83886948 -0.57058886
 -0.97569453 -0.8242937  -0.55877403 -0.96077725 -0.81122391 -0.54315165
 -0.9335191  -0.79602059 -0.50183144 -0.9334876  -0.79779259 -0.50122229
 -0.93657384 -0.79724811 -0.47702468 -0.92264868 -0.7852176  -0.46209525
 -0.91137186 -0.77141722 -0.45068742 -0.89789287 -0.75924533 -0.43649921
 -0.88623059 -0.74469875 -0.42405234 -0.87231519 -0.73510927 -0.40978004
 -0.84843592 -0.70751842 -0.38544041 -0.84634955 -0.70937669 -0.38227261
 -0.85165864 -0.69847302 -0.34532965 -0.83887066 -0.68708779 -0.33210545
 -0.82919775 -0.67473343 -0.32220529 -0.81530921 -0.6619673  -0.30802682
 -0.81910222 -0.64856617 -0.33755655 -0.82003097 -0.6510519  -0.3662419
 -0.89066556 -0.73468824 -0.46348121 -0.98942721 -0.86347092 -0.64135858
 -1.2006357  -1.08655027 -0.90372242 -1.38443

In [151]:
class Logistic_Regression:

   

    def __init__(self):
        self.w=np.zeros(400);
        self.b=1;
        pass;
        
        
    def sigmoid_compute(self,x):
        x=np.transpose(x);
        dot_prod=np.dot(x,self.w);
        z=dot_prod+self.b;
        ##print(z.shape);
        z=float(z);
        return 1/(1+math.exp(-z));
       

    def binary_cross_entropy_loss(self,x,y):
        z1=self.sigmoid_compute(x);
        ##print(z.shape);
        s=-1*(y*math.log(z1,2)+(1-y)*math.log(1-z1,2));
        return s;

    def summed_loss(self,X,Y,n):
        s=0;
        for i in range(n):
            s+=self.binary_cross_entropy_loss(X[i,],Y[i]);
        return s*(1/12499);

    def grads(self,X,Y):
        w_grad=0;
        b_grad=0;
        c=0;
        for i in range(12499):
            c=self.sigmoid_compute(X[i,])-Y[i]
            w_grad+=X[i,]*c;
            b_grad+=c;
        return (w_grad,b_grad);

    def model_train(self,X,Y,e,lr,reg):
        w_t=np.zeros(400);
        b_t=0;
        sub=0;
        fac=(lr/12499);
        for i in range(e):
            wg,bg=self.grads(X,Y);
            w_t=w_t*(1-2*reg*lr)-lr*(1/12499)*wg;
            b_t=b_t-lr*(1/12499)*bg;
            self.w=w_t;
            self.b=b_t;
            print("In epoch: ",i+1, "b=",self.b," loss=",self.summed_loss(X,Y,12499));
    
    def model_test(self,X1,Y1):
        print("Loss = ",self.summed_loss(X1,Y1,X1[1,].shape[0]));







    
        

In [149]:
model1=Logistic_Regression();
model1.model_train(Xtrain_scaled,ytrain,e=1000,lr=0.01,reg=0.01);

In epoch:  1 b= -0.0023413882504967325  loss= 0.9990884336228044
In epoch:  2 b= -0.0023655411274463314  loss= 0.9987883217743392
In epoch:  3 b= -0.0023895232181079737  loss= 0.9985179082339938
In epoch:  4 b= -0.0024134222378822397  loss= 0.9982619224117187
In epoch:  5 b= -0.0024372599716634695  loss= 0.998018288146636
In epoch:  6 b= -0.0024610422728609054  loss= 0.997785847601657
In epoch:  7 b= -0.0024847710551008304  loss= 0.9975636161238143
In epoch:  8 b= -0.0025084472070040684  loss= 0.9973507232322172
In epoch:  9 b= -0.0025320713078841994  loss= 0.9971463964587766
In epoch:  10 b= -0.002555643808180628  loss= 0.9969499493616504
In epoch:  11 b= -0.002579165079045789  loss= 0.9967607711534069
In epoch:  12 b= -0.002602635429544366  loss= 0.9965783176108418
In epoch:  13 b= -0.002626055115478827  loss= 0.996402103098741
In epoch:  14 b= -0.0026494243457324874  loss= 0.9962316935702741
In epoch:  15 b= -0.002672743287605801  loss= 0.996066700424307
In epoch:  16 b= -0.00269601

In [150]:
model1.model_test(Xtest_scaled,ytest);

Loss =  0.0315875158247665
